<?php

declare(strict_types=1);

namespace App\Support;

use Illuminate\Support\Collection;

class GenerateEquipmentCardCatalog
{
    /**
     * @return \Illuminate\Support\Collection<int, array<string, string|bool>>
     */
    public static function all(): Collection
    {
        return collect([
            ['id' => 'row-1', 'document' => '100447', 'equipment_id' => 'EQ-001', 'serial_number' => '0000008-1', 'item_code' => 'E1224/30-40', 'item_name' => 'MOTOR-DRIVEN PUMP', 'counters' => false, 'item_category' => 'Tooling', 'item_group_code' => '124', 'item_group' => 'TOOLS AND GSE', 'in_stock' => 'Yes', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-2', 'document' => '274783', 'equipment_id' => 'EQ-002', 'serial_number' => '0000151', 'item_code' => '3G3130V0251', 'item_name' => 'DATA ACQUISITION UNIT', 'counters' => false, 'item_category' => 'Aircraft Spare', 'item_group_code' => '120', 'item_group' => 'AIRCRAFT SPARES', 'in_stock' => 'Yes', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-3', 'document' => '100446', 'equipment_id' => 'EQ-003', 'serial_number' => '000002-1', 'item_code' => '8G6230G0133', 'item_name' => 'TOOL KIT, SWAGE', 'counters' => true, 'item_category' => 'Tooling', 'item_group_code' => '124', 'item_group' => 'TOOLS AND GSE', 'in_stock' => 'Yes', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-4', 'document' => '100446', 'equipment_id' => 'EQ-004', 'serial_number' => '000002-3', 'item_code' => '8G6700G0553', 'item_name' => 'TOOL KIT, FLEX SHAFT', 'counters' => false, 'item_category' => 'Tooling', 'item_group_code' => '124', 'item_group' => 'TOOLS AND GSE', 'in_stock' => 'Yes', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-5', 'document' => '100444', 'equipment_id' => 'EQ-005', 'serial_number' => '000004-1', 'item_code' => '3G6405G0863', 'item_name' => 'T/R BUSHING REMOVAL TOOL', 'counters' => false, 'item_category' => 'Tooling', 'item_group_code' => '124', 'item_group' => 'TOOLS AND GSE', 'in_stock' => 'Yes', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-6', 'document' => '262818', 'equipment_id' => 'EQ-006', 'serial_number' => '0000547', 'item_code' => '3G3130V0151', 'item_name' => 'HUMS CONTROL UNIT', 'counters' => true, 'item_category' => 'Aircraft Spare', 'item_group_code' => '120', 'item_group' => 'AIRCRAFT SPARES', 'in_stock' => 'Yes', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-7', 'document' => '100444', 'equipment_id' => 'EQ-007', 'serial_number' => '000014-1', 'item_code' => '3G6205G1123', 'item_name' => 'TOOL KIT SWASH PLATE', 'counters' => false, 'item_category' => 'Tooling', 'item_group_code' => '124', 'item_group' => 'TOOLS AND GSE', 'in_stock' => 'Yes', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-8', 'document' => '100444', 'equipment_id' => 'EQ-008', 'serial_number' => '000016-1', 'item_code' => '3G6405G0183', 'item_name' => 'TAIL ROTOR HEAD TOOL', 'counters' => false, 'item_category' => 'Tooling', 'item_group_code' => '124', 'item_group' => 'TOOLS AND GSE', 'in_stock' => 'Yes', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-9', 'document' => '237109', 'equipment_id' => 'EQ-009', 'serial_number' => '000200', 'item_code' => 'STCCLF03003', 'item_name' => 'STRAPS', 'counters' => true, 'item_category' => 'Consumable', 'item_group_code' => '121', 'item_group' => 'CONSUMABLE', 'in_stock' => 'No', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-10', 'document' => '237638', 'equipment_id' => 'EQ-010', 'serial_number' => '000201', 'item_code' => 'STCCLF03003', 'item_name' => 'STRAPS', 'counters' => true, 'item_category' => 'Consumable', 'item_group_code' => '121', 'item_group' => 'CONSUMABLE', 'in_stock' => 'No', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-11', 'document' => '245175', 'equipment_id' => 'EQ-011', 'serial_number' => '000202', 'item_code' => 'STCCLF03003', 'item_name' => 'STRAPS', 'counters' => true, 'item_category' => 'Consumable', 'item_group_code' => '121', 'item_group' => 'CONSUMABLE', 'in_stock' => 'No', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-12', 'document' => '253902', 'equipment_id' => 'EQ-012', 'serial_number' => '000203', 'item_code' => 'STCCLF03003', 'item_name' => 'STRAPS', 'counters' => true, 'item_category' => 'Consumable', 'item_group_code' => '121', 'item_group' => 'CONSUMABLE', 'in_stock' => 'No', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-13', 'document' => '254624', 'equipment_id' => 'EQ-013', 'serial_number' => '000204', 'item_code' => 'STCCLF03003', 'item_name' => 'STRAPS', 'counters' => true, 'item_category' => 'Consumable', 'item_group_code' => '121', 'item_group' => 'CONSUMABLE', 'in_stock' => 'No', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-14', 'document' => '270921', 'equipment_id' => 'EQ-014', 'serial_number' => '000205', 'item_code' => 'STCCLF03003', 'item_name' => 'STRAPS', 'counters' => true, 'item_category' => 'Consumable', 'item_group_code' => '121', 'item_group' => 'CONSUMABLE', 'in_stock' => 'No', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-15', 'document' => '270921', 'equipment_id' => 'EQ-015', 'serial_number' => '000206', 'item_code' => 'STCCLF03003', 'item_name' => 'STRAPS', 'counters' => true, 'item_category' => 'Consumable', 'item_group_code' => '121', 'item_group' => 'CONSUMABLE', 'in_stock' => 'No', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-16', 'document' => '270921', 'equipment_id' => 'EQ-016', 'serial_number' => '000207', 'item_code' => 'STCCLF03003', 'item_name' => 'STRAPS', 'counters' => true, 'item_category' => 'Consumable', 'item_group_code' => '121', 'item_group' => 'CONSUMABLE', 'in_stock' => 'Yes', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-17', 'document' => '270921', 'equipment_id' => 'EQ-017', 'serial_number' => '000208', 'item_code' => 'STCCLF03003', 'item_name' => 'STRAPS', 'counters' => true, 'item_category' => 'Consumable', 'item_group_code' => '121', 'item_group' => 'CONSUMABLE', 'in_stock' => 'Yes', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-18', 'document' => '270921', 'equipment_id' => 'EQ-018', 'serial_number' => '000209', 'item_code' => 'STCCLF03003', 'item_name' => 'STRAPS', 'counters' => true, 'item_category' => 'Consumable', 'item_group_code' => '121', 'item_group' => 'CONSUMABLE', 'in_stock' => 'Yes', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-19', 'document' => '270921', 'equipment_id' => 'EQ-019', 'serial_number' => '000210', 'item_code' => 'STCCLF03003', 'item_name' => 'STRAPS', 'counters' => true, 'item_category' => 'Consumable', 'item_group_code' => '121', 'item_group' => 'CONSUMABLE', 'in_stock' => 'Yes', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-20', 'document' => '270921', 'equipment_id' => 'EQ-020', 'serial_number' => '000211', 'item_code' => 'STCCLF03003', 'item_name' => 'STRAPS', 'counters' => true, 'item_category' => 'Consumable', 'item_group_code' => '121', 'item_group' => 'CONSUMABLE', 'in_stock' => 'Yes', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-21', 'document' => '300145', 'equipment_id' => 'EQ-021', 'serial_number' => 'FX-0001', 'item_code' => 'FA-0001', 'item_name' => 'GROUND POWER UNIT', 'counters' => false, 'item_category' => 'Fixed Asset', 'item_group_code' => '129', 'item_group' => 'FIXED ASSETS', 'in_stock' => 'Yes', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-22', 'document' => '300146', 'equipment_id' => 'EQ-022', 'serial_number' => 'IN-0101', 'item_code' => 'ING-101', 'item_name' => 'HYDRAULIC FLUID', 'counters' => false, 'item_category' => 'Ingredient', 'item_group_code' => '122', 'item_group' => 'INGREDIENTS', 'in_stock' => 'Yes', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
            ['id' => 'row-23', 'document' => '300147', 'equipment_id' => 'EQ-023', 'serial_number' => 'SS-2201', 'item_code' => 'SAFE-2201', 'item_name' => 'LIFE RAFT PACK', 'counters' => false, 'item_category' => 'Safety', 'item_group_code' => '123', 'item_group' => 'SAFETY & SURVIVAL EQP', 'in_stock' => 'No', 'variant' => '', 'operator_code' => '300028', 'operator_name' => '*WESTSTAR', 'owner_code' => '300028', 'owner_name' => '*WESTSTAR', 'status' => 'Serviceable'],
        ]);
    }
}
